/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

int main(void)
{
	uint32_t volatile *pPortAInReg =   (uint32_t*)0x40020010;
	uint32_t *pPortAOutReg =  (uint32_t*)0x40020014;
	// Mode 00 Input 01 Output 0xA800 0000 for port A reset
	uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
	// RCC
	uint32_t *pClkCtrlReg =  (uint32_t*)0x40023830;


	//enable the clock for GPIOA peripherals in the AHB1ENR
	*pClkCtrlReg |= ( 1 << 0);


	//set A0 input
	*pPortAModeReg |= (0 << 0);


	for(;;)
	{
		uint8_t result = (uint8_t)(*pPortAInReg & 0x1) ;
		if (result){
			// make 10th bit position as 1 (SET)
			*pPortAModeReg |= ( 1 << 10);
			//SET 5th bit of the output data register to make I/O pin-5 as HIGH
			*pPortAOutReg |= ( 1 << 5);
		}
		else{
			//b. make 10th bit position as 1 (SET)
			*pPortAModeReg |= ( 1 << 10);
			//Turn OFF the LED
			*pPortAOutReg &= ~( 1 << 5);
		}
	}

	return 0;

}
